sudo: required

language: generic

services:
  - docker

env:
  global:
    - qemu_version=5.1.0-7
    - target_version=0.3.0
  matrix:
    - target_arch=amd64 qemu_arch=x86_64
    - target_arch=armv7 qemu_arch=arm
    - target_arch=armv6 qemu_arch=arm
    - target_arch=arm64 qemu_arch=aarch64

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - mkdir $HOME/.docker
  - 'echo "{" > $HOME/.docker/config.json'
  - 'echo "  \"experimental\": \"enabled\"" >> $HOME/.docker/config.json'
  - 'echo "}" >> $HOME/.docker/config.json'
  - sudo service docker restart
  - mkdir bin

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - curl -sLO https://github.com/multiarch/qemu-user-static/releases/download/v${qemu_version}/qemu-${qemu_arch}-static.tar.gz;
  - tar -xzvf qemu-${qemu_arch}-static.tar.gz;
  - docker build -f Dockerfile.${target_arch} -t ndanyluk/dockerd-exporter-${target_arch}:$TRAVIS_BUILD_NUMBER .

script:
  - sudo docker run -d --name dockerd-exporter ndanyluk/dockerd-exporter-${target_arch}:$TRAVIS_BUILD_NUMBER
  - sudo docker ps | grep -q dockerd-exporter

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    elif [ "$TRAVIS_BRANCH" != "master" ]; then
      echo "Branch build, skipping Docker Hub push";
    else
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker tag ndanyluk/dockerd-exporter-${target_arch}:$TRAVIS_BUILD_NUMBER ndanyluk/dockerd-exporter-${target_arch}:${target_version};
      docker tag ndanyluk/dockerd-exporter-${target_arch}:$TRAVIS_BUILD_NUMBER ndanyluk/dockerd-exporter-${target_arch}:latest;
      docker push ndanyluk/dockerd-exporter-${target_arch}:${target_version};
      docker push ndanyluk/dockerd-exporter-${target_arch}:latest;
    fi

jobs:
  include:
    - stage: deploy
      install: skip
      script: skip
      after_success:
        - if [ -z "$DOCKER_USER" ]; then
            echo "PR build, skipping Docker Hub push";
          elif [ "$TRAVIS_BRANCH" != "master" ]; then
            echo "Branch build, skipping Docker Hub push";
          else
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
            docker manifest create ndanyluk/dockerd-exporter:${target_version} ndanyluk/dockerd-exporter-armv6:${target_version} ndanyluk/dockerd-exporter-arm64:${target_version} ndanyluk/dockerd-exporter-amd64:${target_version};
            docker manifest create ndanyluk/dockerd-exporter:latest ndanyluk/dockerd-exporter-armv6:latest ndanyluk/dockerd-exporter-arm64:latest ndanyluk/dockerd-exporter-amd64:latest;
            docker manifest push ndanyluk/dockerd-exporter:${target_version};
            docker manifest push ndanyluk/dockerd-exporter:latest;
          fi
